<?php
/**
 * @category    MT
 * @package     MT_CatalogSlideshow
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/** @var $this MT_CatalogSlideshow_Block_Widget */
$id = $this->getHtmlId();
?>
<?php if ($this->isShow()): ?>
    <div id="<?php echo $id ?>" class="owl-carousel">
        <?php foreach ($this->getSlides() as $slide): ?>
            <?php if ($slide['link']): ?>
                <a href="<?php echo $slide['link'] ?>" target="<?php echo $slide['target'] ?>">
                    <img class="lazyOwl" data-src="<?php echo strpos($slide['uri'], 'http') === 0 ? $slide['uri'] : Mage::getBaseUrl('media') . $slide['uri'] ?>"/>
                </a>
            <?php else: ?>
                <img src="<?php echo strpos($slide['uri'], 'http') === 0 ? $slide['uri'] : Mage::getBaseUrl('media') . $slide['uri'] ?>"/>
            <?php endif ?>
        <?php endforeach ?>
    </div>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mt/catalogslideshow/main.js"></script>
    <script type="text/javascript">
        new MT.CatalogSlideShow('<?php echo $id ?>', {
            carousel: <?php echo $this->getConfig('carousel') ?>
        });
    </script>
<?php endif ?>
